---
apiVersion: v1
kind: Namespace
metadata:
  name: tomcat-shop
# tomcat-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: tomcat-boxer-pod1
spec:
  containers:
  - name: tomcat-container
    image: tomcat:latest
    ports:
    - containerPort: 8080

# tomcat-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment-boxer1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat-container
        image: krishnamsg/complete-prodcution-e2e-pipeline:1.0.0-24
        ports:
        - containerPort: 8080

# tomcat-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: tomcat-boxer1
spec:
  selector:
    app: tomcat
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort