---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
# tomcat-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: tomcat-boxer-argocd
spec:
  containers:
  - name: tomcat-container
    image: tomcat:latest
    ports:
    - containerPort: 8080

# tomcat-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment-argocd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat-container
        image: krishnamsg/complete-prodcution-e2e-pipeline:1.0.0-24
        ports:
        - containerPort: 8080

# tomcat-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: tomcat-boxer-stage
spec:
  selector:
    app: tomcat
  type: NodePort
  ports:
  - port: 80          # Port exposed within the cluster
    targetPort: 8080  # Port on the pods
    nodePort: 30000   # Port accessible externally on each node